In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
import geopandas as gpd
from IPython.display import Image

In [2]:
volume=pd.read_excel('9_volume.xlsx',sheet_name='2021년 09월')

In [3]:
velocity=pd.read_excel('9_velocity.xlsx')

# 교통량 데이터 위도 경도 합치기 & 불필요한 데이터 지우기

In [4]:
volume.head()

,일자,요일,지점명,지점번호,방향,구분,0시,1시,2시,3시,...,16시,17시,18시,19시,20시,21시,22시,23시,Unnamed: 30,Unnamed: 31
0,20210901,수,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,323.0,243.0,153.0,142.0,...,1840.0,1996.0,1795.0,1327.0,1174.0,1163.0,923.0,595.0,NaN,NaN
1,20210902,목,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,384.0,234.0,175.0,162.0,...,1991.0,1996.0,1849.0,1516.0,1185.0,1127.0,951.0,681.0,NaN,NaN
2,20210903,금,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,362.0,245.0,194.0,168.0,...,2079.0,2157.0,1928.0,1537.0,1383.0,1379.0,1072.0,721.0,NaN,NaN
3,20210904,토,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,423.0,217.0,217.0,161.0,...,1548.0,1612.0,1609.0,1178.0,1136.0,1097.0,871.0,549.0,NaN,NaN
4,20210905,일,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,376.0,220.0,135.0,116.0,...,1442.0,1438.0,1261.0,1128.0,993.0,989.0,770.0,485.0,NaN,NaN

In [5]:
volume_index=pd.read_excel('9_volume.xlsx',sheet_name='수집지점 주소 및 좌표')

In [6]:
merge_volume = pd.merge(volume,volume_index,on='지점번호',how="inner")

In [7]:
merge_volume

,일자,요일,지점명,지점번호,방향,구분,0시,1시,2시,3시,...,23시,Unnamed: 30,Unnamed: 31,지점명칭,위도,경도,주소,도로명 주소,유입 방향,유출방향
0,20210901,수,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,323.0,243.0,153.0,142.0,...,595.0,NaN,NaN,성산로(금화터널),37.568588,126.948436,서울시 서대문구 신촌동 1-142,NaN,[성산로]봉원고가차도->독립문역,[성산로]독립문역->봉원고가차도
1,20210902,목,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,384.0,234.0,175.0,162.0,...,681.0,NaN,NaN,성산로(금화터널),37.568588,126.948436,서울시 서대문구 신촌동 1-142,NaN,[성산로]봉원고가차도->독립문역,[성산로]독립문역->봉원고가차도
2,20210903,금,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,362.0,245.0,194.0,168.0,...,721.0,NaN,NaN,성산로(금화터널),37.568588,126.948436,서울시 서대문구 신촌동 1-142,NaN,[성산로]봉원고가차도->독립문역,[성산로]독립문역->봉원고가차도
3,20210904,토,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,423.0,217.0,217.0,161.0,...,549.0,NaN,NaN,성산로(금화터널),37.568588,126.948436,서울시 서대문구 신촌동 1-142,NaN,[성산로]봉원고가차도->독립문역,[성산로]독립문역->봉원고가차도
4,20210905,일,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,376.0,220.0,135.0,116.0,...,485.0,NaN,NaN,성산로(금화터널),37.568588,126.948436,서울시 서대문구 신촌동 1-142,NaN,[성산로]봉원고가차도->독립문역,[성산로]독립문역->봉원고가차도
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8095,20210926,일,서부간선도로,F-09,유출,목동교->신정교,1570.0,1096.0,789.0,631.0,...,1893.0,NaN,NaN,서부간선도로,37.520965,126.881826,서울시 영등포구 문래동6가 52,서울시 영등포구 영동포로2길 34,[서부간선도로]신정교->목동교,[서부간선도로]목동교->신정교
8096,20210927,월,서부간선도로,F-09,유출,목동교->신정교,1229.0,829.0,591.0,664.0,...,1944.0,NaN,NaN,서부간선도로,37.520965,126.881826,서울시 영등포구 문래동6가 52,서울시 영등포구 영동포로2길 34,[서부간선도로]신정교->목동교,[서부간선도로]목동교->신정교
8097,20210928,화,서부간선도로,F-09,유출,목동교->신정교,1317.0,868.0,667.0,651.0,...,1843.0,NaN,NaN,서부간선도로,37.520965,126.881826,서울시 영등포구 문래동6가 52,서울시 영등포구 영동포로2길 34,[서부간선도로]신정교->목동교,[서부간선도로]목동교->신정교
8098,20210929,수,서부간선도로,F-09,유출,목동교->신정교,1191.0,811.0,621.0,598.0,...,1932.0,NaN,NaN,서부간선도로,37.520965,126.881826,서울시 영등포구 문래동6가 52,서울시 영등포구 영동포로2길 34,[서부간선도로]신정교->목동교,[서부간선도로]목동교->신정교
8099,20210930,목,서부간선도로,F-09,유출,목동교->신정교,1303.0,880.0,612.0,584.0,...,2113.0,NaN,NaN,서부간선도로,37.520965,126.881826,서울시 영등포구 문래동6가 52,서울시 영등포구 영동포로2길 34,[서부간선도로]신정교->목동교,[서부간선도로]목동교->신정교

In [8]:
merge_volume.drop(['Unnamed: 30','Unnamed: 31','지점번호','도로명 주소','유입 방향','유출방향'],axis=1,inplace=True)

In [9]:
merge_volume.drop(['지점명칭','주소'],axis=1,inplace=True)

In [10]:
merge_volume['방향']=merge_volume['방향'].replace({'유입':'상행','유출':'하행'})

In [11]:
merge_volume['종점명']=merge_volume.구분.str.split('->').str[-1]
merge_volume['시점명']=merge_volume.구분.str.split('->').str[0]

In [12]:
merge_volume.drop(['구분'],axis=1,inplace=True)

In [13]:
merge_volume

,일자,요일,지점명,방향,0시,1시,2시,3시,4시,5시,...,18시,19시,20시,21시,22시,23시,위도,경도,종점명,시점명
0,20210901,수,성산로(금화터널),상행,323.0,243.0,153.0,142.0,248.0,621.0,...,1795.0,1327.0,1174.0,1163.0,923.0,595.0,37.568588,126.948436,독립문역,봉원고가차도
1,20210902,목,성산로(금화터널),상행,384.0,234.0,175.0,162.0,307.0,625.0,...,1849.0,1516.0,1185.0,1127.0,951.0,681.0,37.568588,126.948436,독립문역,봉원고가차도
2,20210903,금,성산로(금화터널),상행,362.0,245.0,194.0,168.0,222.0,641.0,...,1928.0,1537.0,1383.0,1379.0,1072.0,721.0,37.568588,126.948436,독립문역,봉원고가차도
3,20210904,토,성산로(금화터널),상행,423.0,217.0,217.0,161.0,240.0,407.0,...,1609.0,1178.0,1136.0,1097.0,871.0,549.0,37.568588,126.948436,독립문역,봉원고가차도
4,20210905,일,성산로(금화터널),상행,376.0,220.0,135.0,116.0,132.0,261.0,...,1261.0,1128.0,993.0,989.0,770.0,485.0,37.568588,126.948436,독립문역,봉원고가차도
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8095,20210926,일,서부간선도로,하행,1570.0,1096.0,789.0,631.0,666.0,978.0,...,2562.0,2859.0,2781.0,2873.0,2608.0,1893.0,37.520965,126.881826,신정교,목동교
8096,20210927,월,서부간선도로,하행,1229.0,829.0,591.0,664.0,1425.0,1995.0,...,2120.0,2245.0,2616.0,2687.0,2628.0,1944.0,37.520965,126.881826,신정교,목동교
8097,20210928,화,서부간선도로,하행,1317.0,868.0,667.0,651.0,1126.0,2122.0,...,1922.0,2256.0,2568.0,2226.0,2339.0,1843.0,37.520965,126.881826,신정교,목동교
8098,20210929,수,서부간선도로,하행,1191.0,811.0,621.0,598.0,935.0,1766.0,...,2238.0,2413.0,2446.0,2719.0,2688.0,1932.0,37.520965,126.881826,신정교,목동교
8099,20210930,목,서부간선도로,하행,1303.0,880.0,612.0,584.0,934.0,1984.0,...,2200.0,2300.0,2708.0,2819.0,2823.0,2113.0,37.520965,126.881826,신정교,목동교

# 링크 아이디 편집하기

In [85]:
link_node=pd.read_excel('tm_link.xlsx')

In [1]:
from pyproj import Transformer
transformer = Transformer.from_crs("epsg:5181", "epsg:4166")

In [4]:
#x=link_node['x'][0]
#y=link_node['y'][0]

transformer.transform(197521.131469,452291.143788)

(35.24249962370125, 129.7715168691593)

In [88]:
x_r=[]
y_r=[]
for i in range(47019):
    x_,y_=link_node['x'][i],link_node['y'][i]
    x_,y_=transformer.transform(y_, x_)
    x_r.append(x_)
    y_r.append(y_)

In [89]:
link_node['위도']=x_r

In [90]:
link_node['경도']=y_r

In [91]:
link_node

,링크아이디,VER_SEQ,x,y,위도,경도
0,1000000100,1,197521.131469,452291.143788,37.570158,126.971940
1,1000000100,2,197476.397972,452270.601508,37.569973,126.971434
2,1000000100,3,197396.282962,452205.291085,37.569384,126.970527
3,1000000100,4,197282.329009,452103.185089,37.568464,126.969238
4,1000000200,1,197290.336956,452094.247932,37.568383,126.969329
...,...,...,...,...,...,...
47014,3201510300,6,193486.440321,449553.923339,37.545476,126.926294
47015,3201510600,1,193191.096253,449512.318965,37.545099,126.922952
47016,3201510600,2,192690.580646,449559.157211,37.545517,126.917288
47017,3201510700,1,192689.462571,449547.209412,37.545409,126.917275
47018,3201510700,2,193189.978178,449500.371166,37.544991,126.922939

In [92]:
link_node=link_node.groupby(link_node['링크아이디']).mean()

# 속도 데이터 구하기

In [99]:
merge_velocity=pd.merge(velocity,link_node,on='링크아이디',how="inner")

In [100]:
merge_velocity.drop(['VER_SEQ','x','y'],axis=1,inplace=True)

In [101]:
idx=merge_velocity[merge_velocity['기능유형구분']=="보조간선도로"].index

In [102]:
idx2=merge_velocity[merge_velocity['기능유형구분']=="기타도로"].index

In [103]:
merge_velocity.drop(idx,inplace=True)
merge_velocity.drop(idx2,inplace=True)

In [104]:
merge_velocity.columns

Index(['일자', '요일', '도로명', '링크아이디', '시점명', '종점명', '방향', '거리', '차선수', '기능유형구분',
       '도심/외곽구분', '권역구분', '01시', '02시', '03시', '04시', '05시', '06시', '07시',
       '08시', '09시', '10시', '11시', '12시', '13시', '14시', '15시', '16시', '17시',
       '18시', '19시', '20시', '21시', '22시', '23시', '24시', '위도', '경도'],
      dtype='object')

In [105]:
merge_velocity.rename(columns={'01시':'1시 속도',
                               '02시':'2시 속도',
                               '03시':'3시 속도', 
                               '04시':'4시 속도',
                               '05시':'5시 속도',
                               '06시':'6시 속도', 
                               '07시':'7시 속도', 
                               '08시':'8시 속도', 
                               '09시':'9시 속도', 
                               '10시':'10시 속도',
                               '11시':'11시 속도',
                               '12시':'12시 속도',
                               '13시':'13시 속도', 
                               '14시':'14시 속도', 
                               '15시':'15시 속도',
                               '16시':'16시 속도', 
                               '17시':'17시 속도', 
                               '18시':'18시 속도',
                               '19시':'19시 속도', 
                               '20시':'20시 속도',
                               '21시':'21시 속도', 
                               '22시':'22시 속도', 
                               '23시':'23시 속도', 
                               '24시':'24시 속도'},inplace=True)

In [106]:
merge_velocity

,일자,요일,도로명,링크아이디,시점명,종점명,방향,거리,차선수,기능유형구분,...,17시 속도,18시 속도,19시 속도,20시 속도,21시 속도,22시 속도,23시 속도,24시 속도,위도,경도
3000,20210901,수,강남대로,1210007700,염곡사거리,국악고교입구,상행,430,5,주간선도로,...,26.01,29.92,27.34,25.79,32.49,30.97,31.98,29.48,37.467127,127.041551
3001,20210902,목,강남대로,1210007700,염곡사거리,국악고교입구,상행,430,5,주간선도로,...,28.38,25.89,22.91,26.68,28.18,29.24,29.63,27.27,37.467127,127.041551
3002,20210903,금,강남대로,1210007700,염곡사거리,국악고교입구,상행,430,5,주간선도로,...,23.75,22.61,15.75,21.26,24.53,28.13,31.66,31.71,37.467127,127.041551
3003,20210904,토,강남대로,1210007700,염곡사거리,국악고교입구,상행,430,5,주간선도로,...,24.35,22.48,26.20,26.53,26.62,35.95,36.48,31.44,37.467127,127.041551
3004,20210905,일,강남대로,1210007700,염곡사거리,국악고교입구,상행,430,5,주간선도로,...,31.07,30.39,29.31,27.83,25.15,29.02,27.12,31.98,37.467127,127.041551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150982,20210929,수,강남순환로,1179920110,금천영업소,본선시점부(금천),하행,273,4,도시고속도로,...,60.00,60.00,60.00,60.00,60.00,60.00,60.00,60.00,37.438265,126.904568
150983,20210930,목,강남순환로,1179920110,금천영업소,본선시점부(금천),하행,273,4,도시고속도로,...,60.00,60.00,60.00,60.00,60.00,60.00,60.00,60.00,37.438265,126.904568
150984,20210906,월,경부고속도로,2040002902,경부고속도로(만남의광장),달래네고개,상행,2716,5,도시고속도로,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.449945,127.052258
150985,20210915,수,경부고속도로,2040002902,경부고속도로(만남의광장),달래네고개,상행,2716,5,도시고속도로,...,NaN,NaN,78.00,NaN,NaN,NaN,NaN,NaN,37.449945,127.052258
150986,20210917,금,경부고속도로,2040002902,경부고속도로(만남의광장),달래네고개,상행,2716,5,도시고속도로,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.449945,127.052258

# 좌표 확인을 위한 folium

In [4]:
import folium as g

In [32]:
g_map=g.Map(location=[35.26535524869505, 130.945070019479],zoom_start=18)
g_map

# 불필요한 열 제거 및 결측치 행 제거

In [132]:
merge_velocity.columns

Index(['일자', '요일', '도로명', '링크아이디', '시점명', '종점명', '방향', '거리', '차선수', '기능유형구분',
       '도심/외곽구분', '권역구분', '1시 속도', '2시 속도', '3시 속도', '4시 속도', '5시 속도', '6시 속도',
       '7시 속도', '8시 속도', '9시 속도', '10시 속도', '11시 속도', '12시 속도', '13시 속도',
       '14시 속도', '15시 속도', '16시 속도', '17시 속도', '18시 속도', '19시 속도', '20시 속도',
       '21시 속도', '22시 속도', '23시 속도', '24시 속도', '위도', '경도'],
      dtype='object')

In [134]:
merge_velocity.drop(['기능유형구분','도심/외곽구분', '권역구분'],axis=1,inplace=True)

In [172]:
drop_velo=merge_velocity.dropna(axis=0)

In [173]:
drop_vol=merge_volume.dropna(axis=0)

# 주말 데이터 제거

In [174]:
idx=drop_velo[drop_velo['요일']=="토"].index

In [175]:
idx2=drop_velo[drop_velo['요일']=="일"].index

In [176]:
drop_velo.drop(idx,inplace=True)
drop_velo.drop(idx2,inplace=True)

C:\Users\keonj\anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [177]:
idx=drop_vol[drop_vol['요일']=="토"].index

In [178]:
idx2=drop_vol[drop_vol['요일']=="일"].index

In [179]:
drop_vol.drop(idx,inplace=True)
drop_vol.drop(idx2,inplace=True)

In [180]:
drop_vol.drop(['일자','요일'],axis=1,inplace=True)

In [181]:
drop_velo.drop(['일자','요일'],axis=1,inplace=True)

In [232]:
drop_vol2=drop_vol.round(3)

In [233]:
drop_velo2=drop_velo.round(3)

In [250]:
drop_vol3=drop_vol.round(3)

In [251]:
drop_velo3=drop_velo.round(3)

# 한 지점당 하나의 데이터로 합치기

In [234]:
drop_vol2.drop(['지점명','종점명','시점명'],axis=1,inplace=True)

In [235]:
drop_vol2=drop_vol2.groupby(['위도','경도','방향']).mean()

In [236]:
drop_vol2

                           0시          1시          2시          3시          4시  \
위도     경도      방향
37.437 126.903 상행  503.421053  322.894737  221.631579  222.947368  448.947368
               하행  452.736842  220.894737  159.105263  164.947368  376.789474
37.449 126.926 상행  307.722222  173.166667  127.333333  136.166667  277.777778
               하행  470.055556  276.555556  201.222222  173.055556  241.833333
37.451 126.892 상행  173.315789   99.631579   75.631579   74.578947  162.000000
...                       ...         ...         ...         ...         ...
37.652 127.061 상행  258.947368  158.894737  111.263158   99.105263  167.789474
               하행  195.210526  124.631579   93.263158   83.210526   86.631579
37.689 127.055 상행  370.315789  260.157895  190.736842  194.421053  358.947368
               하행  415.578947  293.315789  227.947368  255.894737  452.210526
37.692 127.045 하행  331.105263  231.421053  171.578947  167.157895  241.789474

                            5시           6시           7시           8시  \
위도     경도      방향
37.437 126.903 상행  1128.105263  2174.578947  2736.473684  2603.789474
               하행  1212.105263  1825.789474  2471.736842  2138.894737
37.449 126.926 상행  1264.055556  3169.444444  3963.555556  3693.611111
               하행   614.666667  1587.777778  2465.722222  2551.611111
37.451 126.892 상행   346.157895   797.736842  1376.105263  1097.157895
...                        ...          ...          ...          ...
37.652 127.061 상행   343.210526   827.105263  1275.736842  1356.578947
               하행   148.421053   382.157895   910.947368   983.578947
37.689 127.055 상행   735.157895  1287.105263  2390.105263  2836.736842
               하행  1311.263158  2691.947368  4059.789474  3968.421053
37.692 127.045 하행   577.368421  1157.052632  1950.473684  2106.000000

                            9시  ...          14시          15시          16시  \
위도     경도      방향               ...
37.437 126.903 상행  2536.368421  ...  2273.842105  2356.421053  2416.842105
               하행  2197.736842  ...  2156.315789  2288.473684  2412.736842
37.449 126.926 상행  3227.388889  ...  2379.166667  2303.111111  2485.166667
               하행  2217.333333  ...  2404.888889  2623.666667  3143.166667
37.451 126.892 상행  1237.473684  ...  1126.684211  1167.157895  1214.368421
...                        ...  ...          ...          ...          ...
37.652 127.061 상행  1300.473684  ...  1280.052632  1301.105263  1309.000000
               하행   876.526316  ...  1007.578947  1050.421053  1079.894737
37.689 127.055 상행  2516.368421  ...  2541.315789  2686.684211  3085.789474
               하행  2834.894737  ...  2211.052632  2306.947368  2505.000000
37.692 127.045 하행  1497.315789  ...  1194.894737  1212.315789  1307.368421

                           17시          18시          19시          20시  \
위도     경도      방향
37.437 126.903 상행  2513.263158  2489.052632  2330.947368  2108.631579
               하행  2686.578947  2896.315789  2482.526316  1863.526316
37.449 126.926 상행  2660.944444  2563.888889  2144.500000  1677.500000
               하행  3639.222222  3703.611111  3304.000000  2403.055556
37.451 126.892 상행  1310.421053  1250.631579   954.631579   809.263158
...                        ...          ...          ...          ...
37.652 127.061 상행  1300.631579  1265.000000  1116.684211   932.684211
               하행  1089.315789  1071.210526   837.578947   671.052632
37.689 127.055 상행  3289.736842  3077.684211  2974.421053  2376.052632
               하행  2585.789474  2470.842105  1813.526316  1482.736842
37.692 127.045 하행  1439.736842  1492.157895  1306.947368   944.210526

                           21시          22시         23시
위도     경도      방향
37.437 126.903 상행  1796.368421  1438.789474  880.842105
               하행  1494.105263  1131.947368  702.789474
37.449 126.926 상행  1364.722222   993.277778  569.722222
               하행  1852.944444  1641.222222  931.555556
37.451 126.892 상행   684.526316   469.736842  258.894737
...                        ...          ...         ...
37.652 127.061 상행   820.105263   697.578947  430.789474
               하행   609.157895   520.894737  329.736842
37.689 127.055 상행  1782.789474  1287.631579  724.000000
               하행  1277.894737  1122.894737  693.263158
37.692 127.045 하행   878.105263   765.684211  500.263158

[261 rows x 24 columns]

In [237]:
drop_velo2.drop(['도로명','종점명','시점명','링크아이디'],axis=1,inplace=True)

In [238]:
drop_velo2=drop_velo2.groupby(['위도','경도','방향']).mean()

In [239]:
drop_velo2

                      거리  차선수      1시 속도      2시 속도      3시 속도      4시 속도  \
위도     경도      방향
37.436 126.903 상행  503.0  6.0  22.640455  22.085000  20.187727  19.803182
               하행  506.0  5.0  24.033182  24.141818  26.564091  26.074545
37.438 126.905 상행  273.0  4.0  61.250000  61.250000  61.250000  61.250000
               하행  273.0  4.0  61.250000  61.250000  61.250000  61.250000
       126.907 상행  118.0  7.0  94.547619  93.995714  93.455714  93.071905
...                  ...  ...        ...        ...        ...        ...
37.685 127.046 하행  759.0  2.0  29.423636  28.881364  30.688182  31.714091
37.688 127.055 하행  285.0  3.0  58.682273  58.097727  58.290909  61.113182
       127.056 상행  287.0  3.0  57.113636  57.595455  55.420455  58.333636
37.691 127.045 상행  702.0  3.0  37.702273  41.833182  40.163182  41.309091
               하행  703.0  3.0  35.771818  35.294545  35.957273  37.483636

                       5시 속도      6시 속도      7시 속도      8시 속도  ...     15시 속도  \
위도     경도      방향                                              ...
37.436 126.903 상행  24.345000  22.525909  20.540000  20.844091  ...  20.365909
               하행  26.028182  22.555455  18.687727  14.456818  ...  18.057273
37.438 126.905 상행  61.250000  61.250000  61.250000  61.250000  ...  61.250000
               하행  61.250000  61.250000  61.250000  61.250000  ...  61.250000
       126.907 상행  91.647619  90.685714  84.896667  79.583810  ...  83.810000
...                      ...        ...        ...        ...  ...        ...
37.685 127.046 하행  28.722727  27.664545  27.610455  25.228636  ...  22.103636
37.688 127.055 하행  59.950909  59.372273  59.330000  59.150000  ...  54.576364
       127.056 상행  56.624545  52.219545  47.492273  44.003182  ...  46.026818
37.691 127.045 상행  39.672273  36.062273  32.678636  30.103182  ...  29.656364
               하행  37.921818  35.762273  34.444545  31.557273  ...  29.177727

                      16시 속도     17시 속도     18시 속도     19시 속도     20시 속도  \
위도     경도      방향
37.436 126.903 상행  18.842727  19.719545  18.144091  19.660909  22.361818
               하행  17.478636  14.581364  14.676364  14.030909  17.004091
37.438 126.905 상행  61.250000  61.250000  61.250000  61.250000  61.250000
               하행  61.250000  61.250000  61.250000  61.250000  61.250000
       126.907 상행  84.748095  85.261905  85.599048  87.464762  87.752857
...                      ...        ...        ...        ...        ...
37.685 127.046 하행  21.049091  21.665000  18.635909  16.150000  17.208636
37.688 127.055 하행  52.770909  50.316818  35.315909  22.882273  26.878182
       127.056 상행  46.550000  45.553636  47.663182  48.962727  49.804091
37.691 127.045 상행  29.422273  29.328182  29.285000  27.495000  29.627727
               하행  29.080000  29.192273  24.420909  20.953182  21.148182

                      21시 속도     22시 속도     23시 속도     24시 속도
위도     경도      방향
37.436 126.903 상행  23.535000  24.949091  25.218636  24.873636
               하행  19.548182  18.497727  19.521818  22.241364
37.438 126.905 상행  61.250000  61.250000  61.250000  61.250000
               하행  61.250000  61.250000  61.250000  61.250000
       126.907 상행  88.299048  90.329524  92.732857  95.122381
...                      ...        ...        ...        ...
37.685 127.046 하행  23.101818  27.180909  29.336364  31.441818
37.688 127.055 하행  45.923182  56.390909  55.596364  56.874091
       127.056 상행  50.302727  52.450455  52.757273  53.363182
37.691 127.045 상행  29.039545  31.270455  29.570455  32.242727
               하행  26.557273  27.697727  29.111818  32.220455

[1724 rows x 26 columns]

# 데이터 테이블 합치기

In [240]:
final_df=pd.merge(drop_velo2,drop_vol2,how='inner',on=['위도','경도','방향'])

In [241]:
final_df.to_csv('final.csv',index=True)

# 전처리한 데이터 결과

In [252]:
drop_velo3.drop(['링크아이디'],axis=1,inplace=True)

In [255]:
drop_vol3=drop_vol3.groupby(['위도','경도','방향','지점명','종점명','시점명']).mean()

In [257]:
drop_vol3

                                                      0시          1시  \
위도     경도      방향 지점명        종점명      시점명
37.437 126.903 상행 시흥대로(석수역)  기아대교앞    석수역     503.421053  322.894737
               하행 시흥대로(석수역)  석수역      기아대교앞   452.736842  220.894737
37.449 126.926 상행 강남순환로      관악IC     금천요금소   307.722222  173.166667
               하행 강남순환로      금천요금소    관악IC    470.055556  276.555556
37.451 126.892 상행 금하로(광명시계)  시흥대교     신촌사거리   173.315789   99.631579
...                                                  ...         ...
37.652 127.061 상행 동일로(노원역)   중계역      노원역     258.947368  158.894737
               하행 동일로(노원역)   노원역      중계역     195.210526  124.631579
37.689 127.055 상행 동일로(의정부IC) 수락지하차도   의정부IC   370.315789  260.157895
               하행 동일로(의정부IC) 의정부IC    수락지하차도  415.578947  293.315789
37.692 127.045 하행 도봉로(도봉산역)  도봉로의정부시계 도봉산역    331.105263  231.421053

                                                      2시          3시  \
위도     경도      방향 지점명        종점명      시점명
37.437 126.903 상행 시흥대로(석수역)  기아대교앞    석수역     221.631579  222.947368
               하행 시흥대로(석수역)  석수역      기아대교앞   159.105263  164.947368
37.449 126.926 상행 강남순환로      관악IC     금천요금소   127.333333  136.166667
               하행 강남순환로      금천요금소    관악IC    201.222222  173.055556
37.451 126.892 상행 금하로(광명시계)  시흥대교     신촌사거리    75.631579   74.578947
...                                                  ...         ...
37.652 127.061 상행 동일로(노원역)   중계역      노원역     111.263158   99.105263
               하행 동일로(노원역)   노원역      중계역      93.263158   83.210526
37.689 127.055 상행 동일로(의정부IC) 수락지하차도   의정부IC   190.736842  194.421053
               하행 동일로(의정부IC) 의정부IC    수락지하차도  227.947368  255.894737
37.692 127.045 하행 도봉로(도봉산역)  도봉로의정부시계 도봉산역    171.578947  167.157895

                                                      4시           5시  \
위도     경도      방향 지점명        종점명      시점명
37.437 126.903 상행 시흥대로(석수역)  기아대교앞    석수역     448.947368  1128.105263
               하행 시흥대로(석수역)  석수역      기아대교앞   376.789474  1212.105263
37.449 126.926 상행 강남순환로      관악IC     금천요금소   277.777778  1264.055556
               하행 강남순환로      금천요금소    관악IC    241.833333   614.666667
37.451 126.892 상행 금하로(광명시계)  시흥대교     신촌사거리   162.000000   346.157895
...                                                  ...          ...
37.652 127.061 상행 동일로(노원역)   중계역      노원역     167.789474   343.210526
               하행 동일로(노원역)   노원역      중계역      86.631579   148.421053
37.689 127.055 상행 동일로(의정부IC) 수락지하차도   의정부IC   358.947368   735.157895
               하행 동일로(의정부IC) 의정부IC    수락지하차도  452.210526  1311.263158
37.692 127.045 하행 도봉로(도봉산역)  도봉로의정부시계 도봉산역    241.789474   577.368421

                                                       6시           7시  \
위도     경도      방향 지점명        종점명      시점명
37.437 126.903 상행 시흥대로(석수역)  기아대교앞    석수역     2174.578947  2736.473684
               하행 시흥대로(석수역)  석수역      기아대교앞   1825.789474  2471.736842
37.449 126.926 상행 강남순환로      관악IC     금천요금소   3169.444444  3963.555556
               하행 강남순환로      금천요금소    관악IC    1587.777778  2465.722222
37.451 126.892 상행 금하로(광명시계)  시흥대교     신촌사거리    797.736842  1376.105263
...                                                   ...          ...
37.652 127.061 상행 동일로(노원역)   중계역      노원역      827.105263  1275.736842
               하행 동일로(노원역)   노원역      중계역      382.157895   910.947368
37.689 127.055 상행 동일로(의정부IC) 수락지하차도   의정부IC   1287.105263  2390.105263
               하행 동일로(의정부IC) 의정부IC    수락지하차도  2691.947368  4059.789474
37.692 127.045 하행 도봉로(도봉산역)  도봉로의정부시계 도봉산역    1157.052632  1950.473684

                                                       8시           9시  ...  \
위도     경도      방향 지점명        종점명      시점명                               ...
37.437 126.903 상행 시흥대로(석수역)  기아대교앞    석수역     2603.789474  2536.368421  ...
               하행 시흥대로(석수역)  석수역      기아대교앞   2138.894737  2197.736842  ...
37.449 126.926 상행 강남순환로      관악IC     금천요금소   3693.611111  3227.388889  ...
               하행 강남순환로      금천요금소    관악IC    2551.611111  2217.333333  ...
37.451 126.892 상행 금하로(광명시계)  시흥대교     신촌사거리   1097.157895  1237.473684  ...
...                                                   ...          ...  ...
37.652 127.061 상행 동일로(노원역)   중계역      노원역     1356.578947  1300.473684  ...
               하행 동일로(노원역)   노원역      중계역      983.578947   876.526316  ...
37.689 127.055 상행 동일로(의정부IC) 수락지하차도   의정부IC   2836.736842  2516.368421  ...
               하행 동일로(의정부IC) 의정부IC    수락지하차도  3968.421053  2834.894737  ...
37.692 127.045 하행 도봉로(도봉산역)  도봉로의정부시계 도봉산역    2106.000000  1497.315789  ...

                                                      14시          15시  \
위도     경도      방향 지점명        종점명      시점명
37.437 126.903 상행 시흥대로(석수역)  기아대교앞    석수역     2273.842105  2356.421053
               하행 시흥대로(석수역)  석수역      기아대교앞   2156.315789  2288.473684
37.449 126.926 상행 강남순환로      관악IC     금천요금소   2379.166667  2303.111111
               하행 강남순환로      금천요금소    관악IC    2404.888889  2623.666667
37.451 126.892 상행 금하로(광명시계)  시흥대교     신촌사거리   1126.684211  1167.157895
...                                                   ...          ...
37.652 127.061 상행 동일로(노원역)   중계역      노원역     1280.052632  1301.105263
               하행 동일로(노원역)   노원역      중계역     1007.578947  1050.421053
37.689 127.055 상행 동일로(의정부IC) 수락지하차도   의정부IC   2541.315789  2686.684211
               하행 동일로(의정부IC) 의정부IC    수락지하차도  2211.052632  2306.947368
37.692 127.045 하행 도봉로(도봉산역)  도봉로의정부시계 도봉산역    1194.894737  1212.315789

                                                      16시          17시  \
위도     경도      방향 지점명        종점명      시점명
37.437 126.903 상행 시흥대로(석수역)  기아대교앞    석수역     2416.842105  2513.263158
               하행 시흥대로(석수역)  석수역      기아대교앞   2412.736842  2686.578947
37.449 126.926 상행 강남순환로      관악IC     금천요금소   2485.166667  2660.944444
               하행 강남순환로      금천요금소    관악IC    3143.166667  3639.222222
37.451 126.892 상행 금하로(광명시계)  시흥대교     신촌사거리   1214.368421  1310.421053
...                                                   ...          ...
37.652 127.061 상행 동일로(노원역)   중계역      노원역     1309.000000  1300.631579
               하행 동일로(노원역)   노원역      중계역     1079.894737  1089.315789
37.689 127.055 상행 동일로(의정부IC) 수락지하차도   의정부IC   3085.789474  3289.736842
               하행 동일로(의정부IC) 의정부IC    수락지하차도  2505.000000  2585.789474
37.692 127.045 하행 도봉로(도봉산역)  도봉로의정부시계 도봉산역    1307.368421  1439.736842

                                                      18시          19시  \
위도     경도      방향 지점명        종점명      시점명
37.437 126.903 상행 시흥대로(석수역)  기아대교앞    석수역     2489.052632  2330.947368
               하행 시흥대로(석수역)  석수역      기아대교앞   2896.315789  2482.526316
37.449 126.926 상행 강남순환로      관악IC     금천요금소   2563.888889  2144.500000
               하행 강남순환로      금천요금소    관악IC    3703.611111  3304.000000
37.451 126.892 상행 금하로(광명시계)  시흥대교     신촌사거리   1250.631579   954.631579
...                                                   ...          ...
37.652 127.061 상행 동일로(노원역)   중계역      노원역     1265.000000  1116.684211
               하행 동일로(노원역)   노원역      중계역     1071.210526   837.578947
37.689 127.055 상행 동일로(의정부IC) 수락지하차도   의정부IC   3077.684211  2974.421053
               하행 동일로(의정부IC) 의정부IC    수락지하차도  2470.842105  1813.526316
37.692 127.045 하행 도봉로(도봉산역)  도봉로의정부시계 도봉산역    1492.157895  1306.947368

                                                      20시          21시  \
위도     경도      방향 지점명        종점명      시점명
37.437 126.903 상행 시흥대로(석수역)  기아대교앞    석수역     2108.631579  1796.368421
               하행 시흥대로(석수역)  석수역      기아대교앞   1863.526316  1494.105263
37.449 126.926 상행 강남순환로      관악IC     금천요금소   1677.500000  1364.722222
               하행 강남순환로      금천요금소    관악IC    2403.055556  1852.944444
37.451 126.892 상행 금하로(광명시계)  시흥대교     신촌사거리    809.263158   684.526316
...                                                   ...          ...
37.652 127.061 상행 동일로(노원역)   중계역      노원역      932.684211   820.105263
               하행 동일로(노원역)   노원역      중계역      671.052632   609.157895
37.689 127.055 상행 동일로(의정부IC) 수락지하차도   의정부IC   2376.052632  1782.789474
               하행 동일로(의정부IC) 의정부IC    수락지하차도  1482.736842  1277.894737
37.692 127.045 하행 도봉로(도봉산역)  도봉로의정부시계 도봉산역     944.210526   878.105263

                                                      22시         23시
위도     경도      방향 지점명        종점명      시점명
37.437 126.903 상행 시흥대로(석수역)  기아대교앞    석수역     1438.789474  880.842105
               하행 시흥대로(석수역)  석수역      기아대교앞   1131.947368  702.789474
37.449 126.926 상행 강남순환로      관악IC     금천요금소    993.277778  569.722222
               하행 강남순환로      금천요금소    관악IC    1641.222222  931.555556
37.451 126.892 상행 금하로(광명시계)  시흥대교     신촌사거리    469.736842  258.894737
...                                                   ...         ...
37.652 127.061 상행 동일로(노원역)   중계역      노원역      697.578947  430.789474
               하행 동일로(노원역)   노원역      중계역      520.894737  329.736842
37.689 127.055 상행 동일로(의정부IC) 수락지하차도   의정부IC   1287.631579  724.000000
               하행 동일로(의정부IC) 의정부IC    수락지하차도  1122.894737  693.263158
37.692 127.045 하행 도봉로(도봉산역)  도봉로의정부시계 도봉산역     765.684211  500.263158

[263 rows x 24 columns]

In [258]:
drop_vol.to_csv('vol.csv',index=True)

In [253]:
drop_velo3=drop_velo3.groupby(['위도','경도','방향','도로명','종점명','시점명']).mean()

In [254]:
drop_velo3.to_csv('velo.csv',index=True)